create table if not exists public.game_saves (
  id bigint generated by default as identity primary key,
  clerk_user_id text not null,
  player_name text not null,
  semester_key text not null default 'freshman-fall',
  save_data jsonb not null,
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create unique index if not exists game_saves_clerk_user_id_semester_key_idx
on public.game_saves (clerk_user_id, semester_key);

alter table public.game_saves enable row level security;

create policy "Users can view their own game saves"
on public.game_saves
as permissive
for select
to authenticated
using (
  ((select auth.jwt()->>'sub') = clerk_user_id)
);

create policy "Users can insert their own game saves"
on public.game_saves
as permissive
for insert
to authenticated
with check (
  ((select auth.jwt()->>'sub') = clerk_user_id)
);

create policy "Users can update their own game saves"
on public.game_saves
as permissive
for update
to authenticated
using (
  ((select auth.jwt()->>'sub') = clerk_user_id)
)
with check (
  ((select auth.jwt()->>'sub') = clerk_user_id)
);
